spring.application.name=tayta
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/tayta
spring.datasource.username=TU_USUARIO_POSTGRES
spring.datasource.password=TU_PASSWORD_POSTGRES

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.data-rest.enabled=false

# JWT
jwt.secret=TU_JWT_SECRET_BASE64
jwt.expiration-ms=86400000

logging.level.org.springframework.security=DEBUG
